name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install PM2 Globally
        run: sudo npm install -g pm2

      - name: Sync Backend Directory
        run: |
          rsync -av --delete /home/ubuntu/actions-runner-backend/_work/md-ashraful-islam-server/md-ashraful-islam-server/ /home/ubuntu/md-ashraful-islam-server/

      - name: Install Dependencies
        run: |
          cd /home/ubuntu/md-ashraful-islam-server
          npm install

      - name: Restart Backend with PM2
        run: |
          cd /home/ubuntu/md-ashraful-islam-server
          # Kill any process running on port 4000
          sudo fuser -k 4000/tcp || true
          # Stop any existing PM2 process
          pm2 stop md-ashraful-islam-server || true
          # Start the new process
          pm2 start ./index.js --name md-ashraful-islam-server -- -f --port 4000 --no-autorestart
